create database task;
use task;
create table EMPLOYEE(EMPLOYEE_ID int,FIRST_NAME varchar(100),LAST_NAME varchar(10),SALARY int,JOINING_DATE varchar(30),DEPARTMENT varchar(80),primary key(EMPLOYEE_ID));
select*from EMPLOYEE;
insert into EMPLOYEE(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,JOINING_DATE,DEPARTMENT)values(1,'Venkatesh','S',100000,'08/08/2015','BANKING'),(2,'Ragavi','P',75000,'08/08/2015','BUSINESS'),(3,'Gopinath','C',50000,'03/02/2016','PHARMA'),(4,'Dinesh','G',50000,'03/02/2016','INSURANE'),(5,'Saibabu','E',40000,'07/08/2017','SOFTWARE'),(6,'Hasan','S',29000,'07/08/2017','MANUFACTURING'),(7,'Divya','P',33000,'07/08/2017','HEALTHCARE'),(8,'Aravindan','R',40000,'07/08/2017','HEALTHCARE'),(9,'Sathish','MD',45000,'03/02/2016','AUTOMOBILES'),(10,'Prasanth','PKP',34000,'03/02/2016','INSURANE'),(11,'Vijay','R',25684,'03/02/2016','BUSINESS'),(12,'Sivakumar','K',54789,'03/02/2016','SOFTWARE');
create table incentive(EMPLOYEE_REFERENCE_ID int,INCENTIVE_DATE varchar(90),INCENTIVE_AMOUNT int,foreign key(EMPLOYEE_REFERENCE_ID) references EMPLOYEE(EMPLOYEE_ID));
select*from incentive;
insert into incentive(EMPLOYEE_REFERENCE_ID,INCENTIVE_DATE,INCENTIVE_AMOUNT)values(1,'01-FEB-16',5000),(2,'01-FEB-16',3000),(3,'01-FEB-17',4000),(1,'01-JAN-17',4500),(2,'01-JAN-17',3500);
-- 01.GET ALL EMPLOYEE DETAILS FROM THE EMPLOYEE TABLE;
select*from EMPLOYEE;

-- 02.GET FIRST NAME, LAST NAME FROM EMPLOYEE TABLE
select FIRST_NAME,LAST_NAME from EMPLOYEE;

-- 03.GET FIRST NAME FORM EMPLOYEE TABLE USING ALIES NAME "EMPLOYEE NAME"
select FIRST_NAME EMPLOYEE_NAME from EMPLOYEE;

-- 04.GET FIRST NAME FROM EMPLOYEE TABLE IN UPPER CASE 
select upper(FIRST_NAME) from EMPLOYEE;

-- 05.GET FIRST NAME FROM EMPLOYEE TABLE IN LOWER CASE 
select lower(FIRST_NAME) from EMPLOYEE;

-- 06.GET UNIQUE DEPARTMENT FROM EMPLOYEE TABLE;
select distinct DEPARTMENT from EMPLOYEE;

-- 07.SELECT FIRST THREE CHARACTER OF FIRSTNAME FROM EMPLOYEE
select left(FIRST_NAME,3) AS FIRST_NAME from EMPLOYEE;

-- 08.GET POSITION OF 'a' FROM 'RAGAVI' FROM EMPLOYEE
select position("a" in FIRST_NAME) position_of_a_in_ragavi from EMPLOYEE where EMPLOYEE_ID=2;

-- 09.GET FIRSTNAME FROM EMPLOYEE TABLE AFTER REMOVING WHITE SPACES FROM RIGTH SIDE
select rtrim(FIRST_NAME)AS FIRST_NAME from EMPLOYEE;

-- 10.GET FIRSTNAME FROM EMPLOYEE TABLE AFTER REMOVING WHITE SPACES FROM LEFT SIDE
select ltrim(FIRST_NAME)AS FIRST_NAME from EMPLOYEE;

-- 11.GET LENGTH OF FIRST NAME FROM EMPLOYEE TABLE;
select length(FIRST_NAME)from EMPLOYEE;

-- 12.GET FIRST NAME FROM EMPLOYEE TABLE AFTER REPLACING 'A' WITH '$'
select replace(FIRST_NAME,'a','$')from EMPLOYEE;

-- 13.GET FIRST NAME AND LAST NAME AS SINGLE COLUMN FROM EMPLOYEE TABLE SEPERATED BY A'_'
select concat(FIRST_NAME,"_",LAST_NAME)As Seperated_BY from EMPLOYEE;

-- 14.GET FIRSTNAME ,JOINING YEAR,JOINING MONTH,JOINING DATE FROM EMPLOYEE TABLE
select FIRST_NAME,
substring_index(JOINING_DATE,"/",-1)AS JOINING_YEAR,
substring_index(JOINING_DATE,"/",1)AS JOINING_MONTH,
substring_index(substring_index(JOINING_DATE,"/",2),"/",-1)AS JOINING_YEAR from EMPLOYEE;

-- 15.GET ALL EMPLOYEE DETAILS FROM THE EMPLOYEE TABLE ORDER BY FIRST NAME ASCENDING
select * from EMPLOYEE order by FIRST_NAME asc;

-- 16.GET ALL EMPLOYEE DETAILS FROM THE EMPLOYEE TABLE ORDER BY FIRST NAME DESCENDING
select * from EMPLOYEE order by FIRST_NAME desc;

-- 17.GET ALL EMPLOYEE DETAILS FROM THE EMPLOYEE TABLE ORDER BY FIRST NAME ASCENDING AND SALARY DESENDING
select * from EMPLOYEE order by FIRST_NAME asc,SALARY desc;

-- 18.GET ALL EMPLOYEE DETAILS FROM THE EMPLOYEE TABLE WHOSE EMPLOYEE NAME IS 'DINESH'
select*from EMPLOYEE where FIRST_NAME='Dinesh';

-- 19.GET ALL EMPLOYEE DETAILS FROM THE EMPLOYEE TABLE WHOSE EMPLOYEE NAME ARE 'DINESH' AND 'ROY'
select*from EMPLOYEE where FIRST_NAME = ('Dinesh'or'Roy');

-- 20.GET ALL EMPLOYEE DETAILS FROM THE EMPLOYEE TABLE WHOSE EMPLOYEE NAME ARE NOT 'DINESH' AND 'ROY'
select*from EMPLOYEE where FIRST_NAME!= 'Dinesh'and FIRST_NAME!='ROY';

-- 21.GET EMPLOYEE DETAILS FROM EMPLOYEE TABLE WHOSE FIRST  NAME STARTS WITH 'S'
select * from EMPLOYEE where FIRST_NAME like's%';

-- 22.GET EMPLOYEE DETAILS FROM EMPLOYEE TABLE WHOSE FIRST  NAME CONTAINS 'V'
select * from EMPLOYEE where FIRST_NAME like'%v%';

-- 23.GET EMPLOYEE DETAILS FROM EMPLOYEE TABLE WHOSE FIRST  NAME ENDS WITH 'N'
select * from EMPLOYEE where FIRST_NAME like'%n';

-- 24.GET EMPLOYEE DETAILS FROM EMPLOYEE TABLE WHOSE FIRST  NAME ENDS WITH 'N' AND CONTAIN WITH 4 LETTERS
select * from EMPLOYEE where FIRST_NAME like'%n' and '___%';

-- 25.GET EMPLOYEE DETAILS FROM EMPLOYEE TABLE WHOSE FIRST  NAME STARTS WITH 'N' AND CONTAIN WITH 4 LETTERS
select * from EMPLOYEE where FIRST_NAME like'j%' and '___%';

-- 26.GET EMPLOYEE DETAILS FROM EMPLOYEE TABLE  WHO'S SALARY GREATEN THAN 60000
select * from EMPLOYEE where SALARY>60000;

-- 27.GET EMPLOYEE DETAILS FROM EMPLOYEE TABLE  WHO'S SALARY LESS THAN 80000
select * from EMPLOYEE where SALARY<80000;

-- 28.GET EMPLOYEE DETAILS FROM EMPLOYEE TABLE  WHO'S SALARY BETWEEN 50000 AND 80000
select * from EMPLOYEE where SALARY<80000 and SALARY>50000;

-- 29.GET ALL EMPLOYEE DETAILS FROM THE EMPLOYEE TABLE WHOSE EMPLOYEE NAME IS 'VENKATESH' AND 'RAGAVI'
select*from EMPLOYEE where FIRST_NAME='Venkatesh'or FIRST_NAME='Ragavi';

-- 30.GET NAME OF EMPLOYESS FROM EMPLOYEE TABLE WHO HAS '%' IN THE LAST NAME
select * from EMPLOYEE where LAST_NAME='%';

-- 31.GET LAST NAME FROM EMPLOYEE TABLE AFTER REPLACING SPECIAL CHARACTER WITH WHITE SPACE
select REPLACE(LAST_NAME,'%',' ')AS LAST_NAME from EMPLOYEE;

-- 32.GET DEPARTMENT ,TOTAL SALARY WITH RESPECT TO A DEPARTMENT FROM EMPLOYEE TABLE
select DEPARTMENT, sum(SALARY) from EMPLOYEE group by DEPARTMENT;

-- 33.GET DEPARTMENT ,TOTAL SALARY WITH RESPECT TO A DEPARTMENT FROM EMPLOYEE TABLE ORDER BY TOTAL SALARY DESCENDING 
select DEPARTMENT, sum(SALARY) from EMPLOYEE group by DEPARTMENT order by sum(SALARY) desc;

-- 34.GET DEPARTMENT WISE AVERAGE SALARY FROM EMPLOYEE TABLE ORDER BY SALARY ASCENDING
select DEPARTMENT,avg(SALARY)AS SALARY from EMPLOYEE group by DEPARTMENT order by avg(SALARY) asc;

-- 35.GET DEPARTMENT WISE MAXIMUM SALARY FROM EMPLOYEE TABLE ORDER BY SALARY ASCENDING
select DEPARTMENT,max(SALARY)AS SALARY from EMPLOYEE group by DEPARTMENT order by max(SALARY) asc;

-- 36.GET DEPARTMENT WISE MINIMUM SALARY FROM EMPLOYEE TABLE ORDER BY SALARY ASCENDING
select DEPARTMENT,min(SALARY)AS SALARY from EMPLOYEE group by DEPARTMENT order by min(SALARY) asc;

-- 37 SELECT NUMBER OF EMPLOYEE JOINED WITH RESPECT TO YEAR AND MONTH TABLE 
select SUBSTRING_INDEX(JOINING_DATE, '/', -1) AS JOINING_YEAR,
	   SUBSTRING_INDEX(JOINING_DATE, '/', 1) AS JOINING_MONTH,
       COUNT(*) AS EMPLOYEE_COUNT from Employee
group by JOINING_YEAR, JOINING_MONTH order by JOINING_YEAR, JOINING_MONTH;

-- 38 SELECT DEPARTMENT , TOTAL SALARY WITH RESPECT TO TOTAL SALARY GREATER THAN 800000
select DEPARTMENT , sum(SALARY) TOTAL_SALARY from employee group by DEPARTMENT having sum(SALARY)>800000 order by sum(SALARY) desc;

-- 39.SELECT FIRST NAME , INCENTIVE AMOUNT FROM EMPLOYEE AND INCENTIVE TABLE 
select t1.FIRST_NAME , t2.Incentive_Amount from employee t1 join Incentives t2 on t1.EMPLOYEE_ID=t2.Employee_Ref_Id;

-- 40.SELECT FIRST NAME , INCENTIVE AMOUNT FROM EMPLOYEE AND INCENTIVE TABLE WHO HAVE INCENTIVE MORE THAN 3000
select t1.FIRST_NAME , t2.Incentive_Amount from employee t1 join Incentives t2 on t1.EMPLOYEE_ID=t2.Employee_Ref_Id where Incentive_Amount > 3000;

-- 41.SELECT FIRST NAME AND INCENTIVE AMOUNT FROM EMPLOYEEE AND INCENTIVE TABLE EVEN THEY NOT HAVE INCENTIVE
select t1.FIRST_NAME , t2.Incentive_Amount from employee t1  left join Incentives t2 on t1.EMPLOYEE_ID=t2.Employee_Ref_Id;

-- 42 SELECT FIRST NAME AND INCENTIVE AMOUNT FROM EMPLOYEEE AND INCENTIVE TABLE EVEN THEY NOT HAVE INCENTIVE THAN PUT 0
select t1.FIRST_NAME , ifnull(t2.Incentive_Amount,0) from employee t1 left join Incentives t2 on t1.EMPLOYEE_ID=t2.Employee_Ref_Id ;

-- 43 SELECT FIRST NAME , INCENTIVE AMOUNT FROM EMPLOYEE AND INCENTIVE TABLE  WHO GOT INCENTIVE USING LEFT JOIN
select t1.FIRST_NAME , t2.Incentive_Amount from employee t1  left join Incentives t2 on t1.EMPLOYEE_ID=t2.Employee_Ref_Id 
where t2.Incentive_Amount is not null ;

-- 44 select max incentive with respect to employee from employee table and incentive table using sub query
select FIRST_NAME,(select MAX(Incentive_Amount) from Incentives where Employee_Ref_Id = Employee.EMPLOYEE_ID) AS Max_Incentive from Employee;

-- 45 SELECT TOP 2 SALARY FROM THE TABLE
select SALARY TOP_2_SALARY from employee order by SALARY desc limit 2;

-- 46 SELECT TOP N SALARY FROM THE TABLE
select SALARY TOP_10_SALARY from employee order by SALARY desc limit N ;

-- 47 SELECT 2ND HIGHEST SALARY FROM THE TABLE
select SALARY 2ND_HIGHEST_SALARY from employee limit 1 offset 1 ;

-- 48 SELECT Nth HIGHEST SALARY FROM THE TABLE
select SALARY Nth_HIGHEST_VALUE from employee limit 1 offset N-1 ;